import { createRequire } from 'module'; const require = createRequire('/Users/gregory/Workspace/iruri_6mo_thumb/package.json');
const { chromium } = require('playwright'); const b = await chromium.launch(); const BASE = 'http://127.0.0.1:8813/'; const out = {};
const pg = await b.newPage({ viewport: { width: 1280, height: 900 } }); const errs = []; pg.on('pageerror', e => errs.push(String(e)));
await pg.goto(BASE + 'lectures/yonsei-hum.html', { waitUntil: 'load' }); await pg.addStyleTag({ content: 'html{scroll-behavior:auto!important}.rv{opacity:1!important}' });
out.d1280 = await pg.evaluate(() => { const x = s => Math.round(document.querySelector(s).getBoundingClientRect().x); return { hcopyX: x('.hcopy'), hmediaX: x('.hmedia'), order: getComputedStyle(document.querySelector('.hcopy')).order + '/' + getComputedStyle(document.querySelector('.hmedia')).order, cartmsg: !!document.querySelector('.cartmsg[aria-live="polite"][role="status"]'), tocRole: document.querySelectorAll('.toc[role="list"]').length + '/' + document.querySelectorAll('.row[role="listitem"]').length + '/' + document.querySelectorAll('.tocmore[role="presentation"]').length, track: document.querySelector('video track').getAttribute('kind'), ords: [...document.querySelectorAll('.lgrp')].map(g => [...g.querySelectorAll('.row .n')].map(n => n.textContent).join(',').slice(0, 40)), firstSet: (() => { const r = document.querySelectorAll('.lgrp')[2].querySelector('.row'); return r.querySelector('.t').textContent + ' | ' + r.querySelector('.m span').textContent; })(), cta: Math.round(document.querySelector('.buybox .acts .btn').getBoundingClientRect().y) }; });
// 포커스 순서: Tab 으로 진행하며 처음 만나는 hero 안 요소가 카피 열인지
await pg.evaluate(() => window.scrollTo(0, 0)); const seq = []; for (let i = 0; i < 16; i++) { await pg.keyboard.press('Tab'); seq.push(await pg.evaluate(() => { const a = document.activeElement; return (a.closest('.hcopy') ? 'copy' : a.closest('.hmedia') ? 'media' : 'other') + ':' + (a.textContent || a.tagName).trim().slice(0, 10); })); }
out.tabOrder = seq.filter(s => !s.startsWith('other')).slice(0, 5);
// 헤더 검색 포커스 링
await pg.focus('.search input'); out.searchFocus = await pg.evaluate(() => getComputedStyle(document.querySelector('.search')).boxShadow);
// 담기 2회 수량
await pg.evaluate(() => localStorage.removeItem('hh_cart_v1')); await pg.click('.buybox .acts button[data-cart-sku]'); await pg.click('.buybox .acts button[data-cart-sku]'); await pg.waitForTimeout(100);
out.cart2 = await pg.evaluate(() => document.querySelector('.cartmsg').textContent.trim());
// 390: 앵커 b 폭, 목록면·인강실 가이드북 채움, 목록 링크 높이
for (const w of [390, 360]) { const p2 = await b.newPage({ viewport: { width: w, height: 844 } }); await p2.goto(BASE + 'lectures/yonsei-hum.html', { waitUntil: 'load' }); await p2.addStyleTag({ content: 'html{scroll-behavior:auto!important}' }); await p2.evaluate(() => window.scrollTo(0, 1500)); await p2.waitForTimeout(200); out['anch' + w] = await p2.evaluate(() => ({ bw: [...document.querySelectorAll('.anch a b')].map(x => Math.round(x.getBoundingClientRect().width)), overflow: document.querySelector('.anch').scrollWidth - document.querySelector('.anch').clientWidth, solidFold: [...document.querySelectorAll('a,button')].filter(e => { const r = e.getBoundingClientRect(); return r.width > 40 && r.height > 30 && r.top >= 0 && r.bottom <= innerHeight && getComputedStyle(e).backgroundColor === 'rgb(49, 46, 46)'; }).map(e => e.textContent.trim().slice(0, 10)) })); await p2.close(); }
const p3 = await b.newPage({ viewport: { width: 390, height: 844 } });
for (const f of ['lectures.html', 'classroom.html']) { await p3.goto(BASE + f, { waitUntil: 'load' }); await p3.addStyleTag({ content: '.rv{opacity:1!important}' }); out[f] = await p3.evaluate(() => ({ guideBg: getComputedStyle(document.querySelector('.fix a.cta')).backgroundColor, solidFold: [...document.querySelectorAll('a,button')].filter(e => { const r = e.getBoundingClientRect(); return r.width > 40 && r.height > 30 && r.top >= 0 && r.bottom <= innerHeight && getComputedStyle(e).backgroundColor === 'rgb(49, 46, 46)'; }).map(e => e.textContent.trim().slice(0, 12)), linkH: [...document.querySelectorAll('.cr h2 a')].map(a => Math.round(a.getBoundingClientRect().height)) })); }
out.errs = errs; console.log(JSON.stringify(out)); await b.close();
